#!/bin/bash
# The pre install for Squadron Manager
#This simply copies the the PHP config file so it the original isn't overwridden

# Copyright 2014 Micah Gale
#
# This file is a part of Squadron Manager
#
#Squadron Manager is free software licensed under the GNU General Public License version 3.
# You may redistribute and/or modify it under the terms of the GNU General Public License
# version 3 as published by the Free Software Foundation.
#
# Squadron Manager comes without a warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the GNU General Public License version 3 for more
# details.
#
# You should have received the GNU General Public License version 3 with this in GPL.txt
# if not it is available at <http://www.gnu.org/licenses/gpl.txt>. 
mv /etc/php5/apache2/php.ini /etc/php5/apahce2/php.ini.orig